# Key Bindings
## Change prefix from 'Ctrl+B' to 'Ctrl+A'
unbind C-b
set -g prefix C-a

# Reload Config file
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# General
set -g renumber-windows on   # renumber all windows when any window is closed
set -g set-clipboard on      # use system clipboard
setw -g mode-keys vi

# Terminal
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{255}%&%{127}%&%p1%dm'
set -as terminal-overrides ',ghostty*:RGB'
set -as terminal-overrides ',xterm-256color:RGB'

# Mouse
set -g mouse on

# Status Bar
set -g status on
set -g status-interval 1
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100
set -g status-style bg=default,fg=white

set -g status-left "#[fg=#{status-style-fg},bg=#{status-style-bg}] #S "
set -g status-right "#[fg=#{status-style-fg},bg=#{status-style-bg}] %Y-%m-%d %H:%M "

# Key Bindings
# Panes
## Split panes using | and -
### Open new windows and panes in current directory
bind "|" split-window -h -c "#{pane_current_path}"
bind "\\" split-window -fh -c "#{pane_current_path}"

bind "-" split-window -v -c "#{pane_current_path}"
bind "_" split-window -fv -c "#{pane_current_path}"

unbind '"'
unbind '%'

## Swap windows
bind -r "<" swap-window -d -t -1
bind -r "," swap-window -d -t -1

bind -r ">" swap-window -d -t +1
bind -r "." swap-window -d -t +1

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Windows
bind c new-window -c "#{pane_current_path}"
bind n next-window
bind p previous-window
bind R command-prompt "rename-window '%%'"
bind K confirm kill-window

# Sessions
bind d detach-client
bind $ command-prompt "rename-session '%%'"
bind S confirm kill-session

# Copy Mode
bind Enter copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi r send -X rectangle-toggle

bind ? display-popup -E "glow -p ~/.config/tmux/README.md"

# Plugins
run-shell ~/.config/tmux/plugins/tmux-sensible/sensible.tmux
run-shell ~/.config/tmux/plugins/catppuccin/catppuccin.tmux
run-shell ~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell ~/.config/tmux/plugins/tmux-continuum/continuum.tmux

# Continuum
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'iterm'
set -g @continuum-save-interval '15'
